name: "Test & Merge"
on:
  pull_request:
    branches:
      -test
      -main
  push:
    branches:
      -test
      -main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3 #checkout the code

      - name: Install Flutter
        uses: subosito/flutter-action@v2 #install flutter sdk

      - name: fix analysis issues
        uses: dart fix --apply

      - name: format code
        uses: dart format lib

      - name: Run Tests
        run: flutter test  # Execute Flutter tests